Change crates.io link to GitHub repositories for annotate-snippets and miette
markdown-link-check fails for links from crates.io:

```
  ERROR: 2 dead links found!
  [✖] https://crates.io/crates/annotate-snippets/ → Status: 404
  [✖] https://crates.io/crates/miette/ → Status: 404
```

The reason is this crates.io issue: https://github.com/rust-lang/crates.io/issues/788